/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package userinterface.SystemAdminWorkArea;

import Business.City.City;
import Business.EcoSystem;
import Business.Enterprise.Enterprise;
import Business.Enterprise.EnterpriseDirectory;
import java.awt.CardLayout;
import java.awt.Component;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author japangor
 */
public class ManageEnterprisesJPanel extends javax.swing.JPanel {

    /**
     * Creates new form ManageTestCenterJPanel
     */
    JPanel userProcessContainer;
    EcoSystem system;
    EnterpriseDirectory enterprise;
    public ManageEnterprisesJPanel(JPanel userProcessContainer,EcoSystem system) {
        initComponents();
        this.userProcessContainer= userProcessContainer;
        this.system=system;
        this.enterprise=enterprise;
        populaTable();
        populateComboBox();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnCreate = new javax.swing.JButton();
        lblManageTesting = new javax.swing.JLabel();
        txtID = new javax.swing.JTextField();
        lblName = new javax.swing.JLabel();
        txtName = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblEnterprise = new javax.swing.JTable();
        lblID = new javax.swing.JLabel();
        lblCity = new javax.swing.JLabel();
        lblEnterpriseType = new javax.swing.JLabel();
        cmbCity = new javax.swing.JComboBox();
        cmbEnterpriseType = new javax.swing.JComboBox();
        btnBack = new javax.swing.JButton();

        setBackground(new java.awt.Color(255, 255, 255));
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btnCreate.setBackground(new java.awt.Color(0, 0, 0));
        btnCreate.setForeground(new java.awt.Color(255, 255, 255));
        btnCreate.setText("Create");
        btnCreate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCreateActionPerformed(evt);
            }
        });
        add(btnCreate, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 450, -1, -1));

        lblManageTesting.setFont(new java.awt.Font("Helvetica Neue", 1, 24)); // NOI18N
        lblManageTesting.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblManageTesting.setText("Manage Enterprise");
        add(lblManageTesting, new org.netbeans.lib.awtextra.AbsoluteConstraints(-240, 10, 970, -1));
        add(txtID, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 350, 212, 30));

        lblName.setText("Name:");
        add(lblName, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 410, -1, 10));
        add(txtName, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 400, 212, 30));

        tblEnterprise.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Name", "EnterpriseID", "City", "Type"
            }
        ));
        jScrollPane1.setViewportView(tblEnterprise);

        add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 50, 1070, 183));

        lblID.setText("ID:");
        add(lblID, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 360, -1, -1));

        lblCity.setText("City:");
        add(lblCity, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 250, 30, 20));

        lblEnterpriseType.setText("Enterprise Type:");
        add(lblEnterpriseType, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 310, -1, 20));

        cmbCity.setFont(new java.awt.Font("Product Sans", 0, 18)); // NOI18N
        cmbCity.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        cmbCity.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmbCityActionPerformed(evt);
            }
        });
        add(cmbCity, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 250, 210, -1));

        cmbEnterpriseType.setFont(new java.awt.Font("Product Sans", 0, 18)); // NOI18N
        cmbEnterpriseType.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        cmbEnterpriseType.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmbEnterpriseTypeActionPerformed(evt);
            }
        });
        add(cmbEnterpriseType, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 300, 210, -1));

        btnBack.setBackground(new java.awt.Color(0, 0, 0));
        btnBack.setForeground(new java.awt.Color(255, 255, 255));
        btnBack.setText("Back");
        btnBack.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBackActionPerformed(evt);
            }
        });
        add(btnBack, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 20, -1, -1));
    }// </editor-fold>//GEN-END:initComponents

    private void btnCreateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCreateActionPerformed
        City city = (City) cmbCity.getSelectedItem();
        Enterprise.EnterpriseType type = (Enterprise.EnterpriseType) cmbEnterpriseType.getSelectedItem();
        String name = txtName.getText();
        int id = Integer.parseInt(txtID.getText());
        if(!city.getEnterpriseDirectory().checkIfIDIsDiff(id)){
            JOptionPane.showMessageDialog(null, String.format("Enterprise ID %s already exists!", id),"Warning",JOptionPane.ERROR_MESSAGE);
        }
        else if (city == null || type == null || name == null ) {
            JOptionPane.showMessageDialog(null, "Invalid Input!"); 
            return;
        }
        else{
            Enterprise enterprise = city.getEnterpriseDirectory().createAddEnterprise(name , type, id);

        }
//        System.out.print(city.getEnterpriseDirectory().checkIfEnterpriseNameIsDiff(name));
//        if (city.getEnterpriseDirectory().checkIfEnterpriseNameIsDiff(name) != true) {
//                JOptionPane.showMessageDialog(null, "Enterprise name exists");
//                    return;
//        }
//        else if(!enterprise.checkIfEnterpriseNameIsDiff(name)){
//            JOptionPane.showMessageDialog(null, String.format("Enterprise Name %s already exists!", name),"Warning",JOptionPane.ERROR_MESSAGE);
//        }
       
        //Enterprise enterprise = city.getEnterpriseDirectory().createAddEnterprise(name , type, id);

        populaTable();
        txtName.setText("");
        txtID.setText("");
    }//GEN-LAST:event_btnCreateActionPerformed

    private void cmbEnterpriseTypeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmbEnterpriseTypeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cmbEnterpriseTypeActionPerformed

    private void btnBackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBackActionPerformed
        // TODO add your handling code here:
        userProcessContainer.remove(this);
        Component[] componentArray = userProcessContainer.getComponents();
        Component component = componentArray[componentArray.length - 1];
        SystemAdminWorkAreaJPanel sysAdminwjp = (SystemAdminWorkAreaJPanel) component;
               sysAdminwjp.populateTree();
        CardLayout layout = (CardLayout) userProcessContainer.getLayout();
        layout.previous(userProcessContainer);

    }//GEN-LAST:event_btnBackActionPerformed

    private void cmbCityActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmbCityActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cmbCityActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnBack;
    private javax.swing.JButton btnCreate;
    private javax.swing.JComboBox cmbCity;
    private javax.swing.JComboBox cmbEnterpriseType;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lblCity;
    private javax.swing.JLabel lblEnterpriseType;
    private javax.swing.JLabel lblID;
    private javax.swing.JLabel lblManageTesting;
    private javax.swing.JLabel lblName;
    private javax.swing.JTable tblEnterprise;
    private javax.swing.JTextField txtID;
    private javax.swing.JTextField txtName;
    // End of variables declaration//GEN-END:variables

    private void populaTable() {
        DefaultTableModel model = (DefaultTableModel) tblEnterprise.getModel();

        model.setRowCount(0);
        for (City city : system.getCityList()) {
            for (Enterprise enterprise : city.getEnterpriseDirectory().getEnterpriseList()) {
                Object[] row = new Object[4];
                row[0] = enterprise;
                row[1] = enterprise.getEnterpriseId();
                row[2] = city.getName();
                row[3] = enterprise.getEnterpriseType().getValue();

                model.addRow(row);
            }
        }//To change body of generated methods, choose Tools | Templates.
    }

    private void populateComboBox() {
        cmbCity.removeAllItems();
        cmbEnterpriseType.removeAllItems();

        for (City city : system.getCityList()) {
            cmbCity.addItem(city);
        }

        for (Enterprise.EnterpriseType type : Enterprise.EnterpriseType.values()) {
            cmbEnterpriseType.addItem(type);
        } 
    }
}
