/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package userinterface.VaccineManufacturer;

import Business.City.City;
import Business.EcoSystem;
import Business.Enterprise.Enterprise;
import Business.Enterprise.VaccineManufacturer;
import Business.Organization.Organization;
import Business.UserAccount.UserAccount;
import Business.Vaccine.Vaccine;
import Business.Vaccine.VaccineDirectory;
import java.awt.CardLayout;
import java.awt.Component;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author hetalp
 */
public class ManageInventoryJPanel extends javax.swing.JPanel {

    /**
     * Creates new form ManageInventoryJPanel
     */
    JPanel userProcessContainer;
    EcoSystem system;
    UserAccount userAccount;
    Organization organization;
    Enterprise enterprise;
    City city;
    //VaccineManufacturer e =(VaccineManufacturer)enterprise;
    public ManageInventoryJPanel(JPanel userProcessContainer,City city,UserAccount userAccount,Organization organization,Enterprise enterprise,EcoSystem system) {
        initComponents();
        this.userProcessContainer=userProcessContainer;
        this.system=system;
        this.userAccount=userAccount;
        this.city=city;
        this.organization=organization;
        this.enterprise=enterprise;
        //VaccineManufacturer e =(VaccineManufacturer)enterprise;
        populaTable();
    }
    //VaccineManufacturer e =(VaccineManufacturer)enterprise;

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblManageInventory = new javax.swing.JLabel();
        lblAvailability = new javax.swing.JLabel();
        txtAvailability = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblVaccineInventory = new javax.swing.JTable();
        btnAdd = new javax.swing.JButton();
        btnDelete = new javax.swing.JButton();
        lblBatch = new javax.swing.JLabel();
        txtBatchNo = new javax.swing.JTextField();
        txtQuantity = new javax.swing.JTextField();
        lblQuantity = new javax.swing.JLabel();
        txtStatus = new javax.swing.JTextField();
        lblStatus = new javax.swing.JLabel();
        btnUpdate = new javax.swing.JButton();
        btnView = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        txtName = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();

        setBackground(new java.awt.Color(255, 255, 255));
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lblManageInventory.setFont(new java.awt.Font("Helvetica Neue", 1, 24)); // NOI18N
        lblManageInventory.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblManageInventory.setText("MANAGE VACCINE INVENTORY");
        add(lblManageInventory, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 10, 620, -1));

        lblAvailability.setFont(new java.awt.Font("Helvetica Neue", 1, 13)); // NOI18N
        lblAvailability.setText("Available Vaccine Stock:");
        add(lblAvailability, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 50, -1, -1));

        txtAvailability.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtAvailabilityActionPerformed(evt);
            }
        });
        add(txtAvailability, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 50, 220, -1));

        tblVaccineInventory.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Name", "Batch Number", "Quantity", "Status"
            }
        ));
        jScrollPane1.setViewportView(tblVaccineInventory);

        add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 80, 951, 181));

        btnAdd.setBackground(new java.awt.Color(0, 0, 0));
        btnAdd.setForeground(new java.awt.Color(255, 255, 255));
        btnAdd.setText("Add");
        btnAdd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAddActionPerformed(evt);
            }
        });
        add(btnAdd, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 420, -1, -1));

        btnDelete.setBackground(new java.awt.Color(0, 0, 0));
        btnDelete.setForeground(new java.awt.Color(255, 255, 255));
        btnDelete.setText("Delete");
        btnDelete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDeleteActionPerformed(evt);
            }
        });
        add(btnDelete, new org.netbeans.lib.awtextra.AbsoluteConstraints(1080, 450, -1, -1));

        lblBatch.setFont(new java.awt.Font("Helvetica Neue", 1, 13)); // NOI18N
        lblBatch.setText("Batch No:");
        add(lblBatch, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 310, -1, -1));
        add(txtBatchNo, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 310, 200, -1));
        add(txtQuantity, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 350, 200, -1));

        lblQuantity.setFont(new java.awt.Font("Helvetica Neue", 1, 13)); // NOI18N
        lblQuantity.setText("Quantity:");
        add(lblQuantity, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 350, -1, -1));
        add(txtStatus, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 390, 200, -1));

        lblStatus.setFont(new java.awt.Font("Helvetica Neue", 1, 13)); // NOI18N
        lblStatus.setText("Status:");
        add(lblStatus, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 400, -1, -1));

        btnUpdate.setBackground(new java.awt.Color(0, 0, 0));
        btnUpdate.setForeground(new java.awt.Color(255, 255, 255));
        btnUpdate.setText("Update");
        btnUpdate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnUpdateActionPerformed(evt);
            }
        });
        add(btnUpdate, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 420, -1, -1));

        btnView.setBackground(new java.awt.Color(0, 0, 0));
        btnView.setForeground(new java.awt.Color(255, 255, 255));
        btnView.setText("View");
        btnView.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnViewActionPerformed(evt);
            }
        });
        add(btnView, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 270, -1, -1));

        jLabel1.setFont(new java.awt.Font("Helvetica Neue", 1, 13)); // NOI18N
        jLabel1.setText("Name");
        add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 280, -1, -1));
        add(txtName, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 280, 200, -1));

        jButton1.setBackground(new java.awt.Color(0, 0, 0));
        jButton1.setForeground(new java.awt.Color(255, 255, 255));
        jButton1.setText("Refresh");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(980, 450, -1, -1));

        jButton2.setBackground(new java.awt.Color(0, 0, 0));
        jButton2.setForeground(new java.awt.Color(255, 255, 255));
        jButton2.setText("Back");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 10, -1, -1));
    }// </editor-fold>//GEN-END:initComponents

    private void btnAddActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAddActionPerformed
        
         int qty;
         int batchId;
         String status;
         String name;
         qty = Integer.parseInt(txtQuantity.getText());
         batchId = Integer.parseInt(txtBatchNo.getText());
         status = txtStatus.getText();
         name = txtName.getText();
         VaccineManufacturer e =(VaccineManufacturer)enterprise;
         System.out.println(e.getVaccineDirectory().getVaccDir());
         Vaccine v = e.getVaccineDirectory().addVaccDir(qty, batchId, status, name);
         /*v.setBatchId(batchId);
         v.setName(name);
         v.setQty(qty);
         v.setStatus(status);*/
         populaTable();
         
         
    }//GEN-LAST:event_btnAddActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        VaccineManufacturer e =(VaccineManufacturer)enterprise;
        int count = 0;
        for(Vaccine vaccine: e.getVaccineDirectory().getVaccDir()){
          count = count+vaccine.getQty();
        }
        txtAvailability.setText(String.valueOf(count));
        populaTable();
    }//GEN-LAST:event_jButton1ActionPerformed

    private void txtAvailabilityActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtAvailabilityActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtAvailabilityActionPerformed

    private void btnViewActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnViewActionPerformed
        int selectRow = tblVaccineInventory.getSelectedRow();
        //VaccineManufacturer e =(VaccineManufacturer)enterprise;
        if(selectRow>=0){
            String name= (String) tblVaccineInventory.getValueAt(selectRow, 0);
            int BatchID= (int) tblVaccineInventory.getValueAt(selectRow, 1);
            int Quantity = (int) tblVaccineInventory.getValueAt(selectRow, 2);
            String status= (String) tblVaccineInventory.getValueAt(selectRow, 3);
            
            txtName.setText(name);
            txtBatchNo.setText(String.valueOf(BatchID));
            txtQuantity.setText(String.valueOf(Quantity));
            txtStatus.setText(status);
        }
        else {
            JOptionPane.showMessageDialog(null,"Please select a row");
        }
    }//GEN-LAST:event_btnViewActionPerformed

    private void btnUpdateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnUpdateActionPerformed
        VaccineManufacturer e =(VaccineManufacturer)enterprise;
        int qty=Integer.parseInt(txtQuantity.getText());
        int batchId=Integer.parseInt(txtBatchNo.getText());
        String status=txtStatus.getText();
        String name=txtName.getText();
        
        for(Vaccine v: e.getVaccineDirectory().getVaccDir()){
            if(v.getBatchId()==batchId){
                v.setName(name);
                v.setQty(qty);
                v.setStatus(status);
            }
        }
        
        
    }//GEN-LAST:event_btnUpdateActionPerformed

    private void btnDeleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDeleteActionPerformed
        VaccineManufacturer e =(VaccineManufacturer)enterprise;
        int batchId=Integer.parseInt(txtBatchNo.getText());
        for(Vaccine v: e.getVaccineDirectory().getVaccDir()){
            if(v.getBatchId()==batchId){
                e.getVaccineDirectory().getVaccDir().remove(v);
            }
        }
    }//GEN-LAST:event_btnDeleteActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        userProcessContainer.remove(this);
        Component[] componentArray = userProcessContainer.getComponents();
        Component component = componentArray[componentArray.length - 1];
        VaccineManufacturerAdminJPanel manageOrderjp = (VaccineManufacturerAdminJPanel) component;
        //        sysAdminwjp.populateTree();
        CardLayout layout = (CardLayout) userProcessContainer.getLayout();
        layout.previous(userProcessContainer);
    }//GEN-LAST:event_jButton2ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAdd;
    private javax.swing.JButton btnDelete;
    private javax.swing.JButton btnUpdate;
    private javax.swing.JButton btnView;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lblAvailability;
    private javax.swing.JLabel lblBatch;
    private javax.swing.JLabel lblManageInventory;
    private javax.swing.JLabel lblQuantity;
    private javax.swing.JLabel lblStatus;
    private javax.swing.JTable tblVaccineInventory;
    private javax.swing.JTextField txtAvailability;
    private javax.swing.JTextField txtBatchNo;
    private javax.swing.JTextField txtName;
    private javax.swing.JTextField txtQuantity;
    private javax.swing.JTextField txtStatus;
    // End of variables declaration//GEN-END:variables

    private void populaTable() {
         DefaultTableModel dtm = (DefaultTableModel) tblVaccineInventory.getModel();
        dtm.setRowCount(0);

                VaccineManufacturer vm =(VaccineManufacturer)enterprise;
                for (Vaccine vaccine : vm.getVaccineDirectory().getVaccDir()) {
                    
                    Object[] row = new Object[4];
                    row[0] = vaccine.getName();
                    row[1] = vaccine.getBatchId();
                    row[2] = vaccine.getQty();
                    row[3] = vaccine.getStatus();
                   
                   

                    dtm.addRow(row);
                
                } //To change body of generated methods, choose Tools | Templates.
    }
}
